[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[script]
maxSessionLifetime = 3600  # Increase the session lifetime to 1 hour (3600 seconds)